In [41]:
def get_computer_choice():
    import random as rd
    list = ["Rock", "Scissors", "Paper"]
    global computer
    computer = (rd.choice(list))
    print(computer)
    return computer

get_computer_choice()



Paper


'Paper'

In [72]:
import time

def countdown(t):
     while t > 0 :
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
        
     return t

countdown(3)
    


0

In [79]:


def get_prediction():
    import cv2
    import time
    from keras.models import load_model
    import numpy as np
    model = load_model('keras_model.h5')
    cap = cv2.VideoCapture(0)
    # Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

       
    t = 5
    while t > 0:
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
        
    

  
    
        ret, frame = cap.read()
        
        
        #resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        #turn the image into a numpy array
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        # Load the image into the array
        data[0] = normalized_image
        global prediction
        prediction = model.predict(data)

        if prediction[0][0] > 0.5:
            print('Rock')
        elif prediction[0][1] > 0.5:
            print('Paper')
        elif prediction[0][2] > 0.5:
            print('Scissors')
        else: 
            print('Nothing')
        cv2.imshow('frame', frame)
        # Press q to close the window
        print(prediction)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break


    # After the loop release the cap object
    cap.release()
    # Destroy all the windows
    cv2.destroyAllWindows()
   
    

    if prediction[0][0] > 0.5:
        prediction = 'Rock'
    elif prediction[0][1] > 0.5:
        prediction = 'Paper'
    elif prediction[0][2] > 0.5:
        prediction = 'Scissors'
    else: 
        prediction = Nothing 
    
    return prediction

    

 



In [80]:
get_prediction()

1/1 [==============================] - 1s 549ms/step
Nothing
[[9.9429544e-03 5.5402466e-05 3.7730226e-01 6.1269939e-01]]
1/1 [==============================] - 0s 33ms/step
Nothing
[[1.4647284e-02 3.2919652e-05 2.3464684e-01 7.5067294e-01]]
1/1 [==============================] - 0s 37ms/step
Paper
[[2.6181564e-07 9.9995327e-01 4.6261779e-05 1.9302753e-07]]
1/1 [==============================] - 0s 32ms/step
Paper
[[1.0536272e-06 9.9970102e-01 2.9546695e-04 2.4634928e-06]]
1/1 [==============================] - 0s 31ms/step
Paper
[[2.6264158e-06 9.9906892e-01 9.2562148e-04 2.8555107e-06]]


'Paper'

In [82]:
def get_winner(computer_guess, model_prediction):

  

    if computer == 'Rock' and prediction == 'Scissors':
        return('Computer wins!')
    elif computer == 'Scissors' and prediction == 'Rock':
        return('You win!')
    elif computer == 'Scissors' and prediction == 'Paper':
        return('Computer wins!')
    elif computer == 'Paper' and prediction == 'Scissors':
        return('You win!')
    elif computer == 'Paper' and prediction == 'Rock':
        return('Computer wins!')
    elif computer == 'Rock' and prediction == 'Paper':
        return('You win!')
    elif computer ==  prediction:
        return('It\'s a draw!')
    else: print('Make your move using "Rock, Scissors or Paper"')
    
    get_winner(computer, prediction) 

In [84]:
def play():
    get_computer_choice()
    get_prediction()
    get_winner(computer, prediction)
    print('You chose', prediction)
    print('The computer chooses', computer)
    print(get_winner(computer, prediction))
        
play()

Rock
1/1 [==============================] - 1s 545ms/step
Nothing
[[0.24381651 0.00160756 0.04735811 0.7072179 ]]
1/1 [==============================] - 0s 31ms/step
Nothing
[[0.11546766 0.003104   0.44918326 0.43224505]]
1/1 [==============================] - 0s 34ms/step
Rock
[[8.6942166e-01 4.6203221e-04 4.5924596e-03 1.2552390e-01]]
1/1 [==============================] - 0s 30ms/step
Rock
[[0.71895343 0.00323712 0.01804304 0.25976637]]
1/1 [==============================] - 0s 30ms/step
Rock
[[8.3670062e-01 3.6151859e-04 1.8794424e-03 1.6105847e-01]]
You chose Rock
The computer chooses Rock
It's a draw!


In [ ]:
class first_to_3():
    
    
