In [ ]:
def get_computer_choice():
    import random as rd
    list = ["Rock", "Scissors", "Paper"]
    global computer
    computer = (rd.choice(list))
    print(computer)
    return computer

get_computer_choice()



In [ ]:
import time

def countdown(t):
     while t > 0 :
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
        
     return t

countdown(3)
    


In [ ]:


def get_prediction():
    import cv2
    import time
    from keras.models import load_model
    import numpy as np
    model = load_model('keras_model.h5')
    cap = cv2.VideoCapture(0)
    # Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

       
    t = 5
    while t > 0:
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
        
    

  
    
        ret, frame = cap.read()
        
        
        #resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        #turn the image into a numpy array
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        # Load the image into the array
        data[0] = normalized_image
        global prediction
        prediction = model.predict(data)

        if prediction[0][0] > 0.5:
            print('Rock')
        elif prediction[0][1] > 0.5:
            print('Paper')
        elif prediction[0][2] > 0.5:
            print('Scissors')
        else: 
            print('Nothing')
        cv2.imshow('frame', frame)
        # Press q to close the window
        print(prediction)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break


    # After the loop release the cap object
    cap.release()
    # Destroy all the windows
    cv2.destroyAllWindows()
   
    

    if prediction[0][0] > 0.5:
        prediction = 'Rock'
    elif prediction[0][1] > 0.5:
        prediction = 'Paper'
    elif prediction[0][2] > 0.5:
        prediction = 'Scissors'
    else: 
        prediction = Nothing 
    
    return prediction

    

 



In [ ]:
get_prediction()

In [ ]:
def get_winner(computer_guess, model_prediction):

  

    if computer == 'Rock' and prediction == 'Scissors':
        return('Computer wins!')
    elif computer == 'Scissors' and prediction == 'Rock':
        return('You win!')
    elif computer == 'Scissors' and prediction == 'Paper':
        return('Computer wins!')
    elif computer == 'Paper' and prediction == 'Scissors':
        return('You win!')
    elif computer == 'Paper' and prediction == 'Rock':
        return('Computer wins!')
    elif computer == 'Rock' and prediction == 'Paper':
        return('You win!')
    elif computer ==  prediction:
        return('It\'s a draw!')
    else: print('Make your move using "Rock, Scissors or Paper"')
    
    get_winner(computer, prediction) 

In [ ]:
def play():
    get_computer_choice()
    get_prediction()
    get_winner(computer, prediction)
    print('You chose', prediction)
    print('The computer chooses', computer)
    print(get_winner(computer, prediction))
        
play()

In [133]:
import random as rd
import cv2
import time

class Rock_paper_scissors():
    
    
    def __init__(self, first_to_x):
        self.first_to_x = first_to_x
        self.score_count_computer = 0
        self.score_count_player = 0

    def get_computer_choice(self):
    
        list = ["Rock", "Scissors", "Paper"]
        self.computer = rd.choice(list)
        return self.computer

    def get_prediction(self):
    
        from keras.models import load_model
        import numpy as np
        model = load_model('keras_model.h5')
        cap = cv2.VideoCapture(0)
        # Create the array of the right shape to feed into the keras model
    # The 'length' or number of images you can put into the array is
    # determined by the first position in the shape tuple, in this case 1.
        data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

        print('5 second count down to make your move!')   
        t = 5
        while t > 0:
            mins, secs = divmod(t, 60)
            timer = '{:02d}:{:02d}'.format(mins, secs)
            print(timer, end="\r")
            time.sleep(1)
            t -= 1
            
            ret, frame = cap.read()
            
            
            #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            #turn the image into a numpy array
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            # Load the image into the array
            data[0] = normalized_image
            global prediction
            prediction = model.predict(data)
            cv2.imshow('frame', frame)
            # Press q to close the window
            print(prediction)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break


        # After the loop release the cap object
        cap.release()
        # Destroy all the windows
        cv2.destroyAllWindows()
    
        

        if prediction[0][0] > 0.5:
            prediction = 'Rock'
        elif prediction[0][1] > 0.5:
            prediction = 'Paper'
        elif prediction[0][2] > 0.5:
            prediction = 'Scissors'
        else: 
            prediction = 'Nothing'
        
        return prediction


    def get_winner(self):

        print('You chose', prediction)
        print('The computer chooses', self.computer)

        if self.computer == 'Rock' and prediction == 'Scissors':
            print('Computer wins this round!')
            self.score_count_computer += 1
            
        elif self.computer == 'Scissors' and prediction == 'Rock':
            print('You win this round!')
            self.score_count_player += 1
            
        elif self.computer == 'Scissors' and prediction == 'Paper':
            print('Computer wins this round!')
            self.score_count_computer += 1
            
        elif self.computer == 'Paper' and prediction == 'Scissors':
            print('You win this round!')
            self.score_count_player += 1
            
        elif self.computer == 'Paper' and prediction == 'Rock':
            print('Computer wins this round!')
            self.score_count_computer += 1
            
        elif self.computer == 'Rock' and prediction == 'Paper':
            print('You win this round!')
            self.score_count_player += 1
            
        elif self.computer ==  prediction:
            print('This round is a draw!')
            
        else: print('Make your move using "Rock, Scissors or Paper"')
        
        print(f'Your score is {int(self.score_count_player)}')   
        print(f'The computer score is {int(self.score_count_computer)}')    
        return (self.score_count_player) and (self.score_count_computer)
     

play_game = Rock_paper_scissors(first_to_x=3)
while play_game.score_count_computer < 3 and play_game.score_count_player < 3:
            
        play_game.get_computer_choice()
        play_game.get_prediction()
        play_game.get_winner()
        if play_game.score_count_computer == play_game.first_to_x:
            print("Computer wins the game!")
            break
        elif play_game.score_count_player == play_game.first_to_x:
            print("Congratulations, You win the game!")
            break
            
play_game

 

    


5 second count down to make your move!
1/1 [==============================] - 1s 552ms/step
[[5.0288077e-02 3.1211373e-04 9.1555768e-01 3.3842128e-02]]
1/1 [==============================] - 0s 38ms/step
[[4.9497618e-07 9.9918836e-01 8.0951274e-04 1.6539725e-06]]
1/1 [==============================] - 0s 33ms/step
[[4.6243687e-05 9.9767655e-01 2.2187056e-03 5.8489339e-05]]
1/1 [==============================] - 0s 38ms/step
[[8.0306916e-07 9.9990594e-01 9.1435846e-05 1.8065128e-06]]
1/1 [==============================] - 0s 31ms/step
[[1.2446285e-06 9.9993753e-01 5.4326680e-05 6.8759337e-06]]
You chose Paper
The computer chooses Scissors
Computer wins this round!
Your score is 0
The computer score is 1
5 second count down to make your move!
1/1 [==============================] - 1s 542ms/step
[[0.00115102 0.00124533 0.9669438  0.03065981]]
1/1 [==============================] - 0s 41ms/step
[[2.7658990e-07 9.9997425e-01 2.5221583e-05 2.7981315e-07]]
1/1 [==============================]

In [129]:
def get_computer_choice(self):
    
        list = ["Rock", "Scissors", "Paper"]
        self.computer = (rd.choice(list))
        print(self.computer)
        return self.computer
get_computer_choice

<function __main__.get_computer_choice(self)>